# -*- coding: utf-8 -*-
"""RP 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L-ZindW-OaxGZMx0niw9vOBxYJ2jDoz-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files  #code to import file
uploaded = files.upload()

dp=pd.read_csv('diabetes_prediction_dataset.csv.zip')
dp

# reads the first five patient details
dp.head()

# reads the last five patients details
dp.tail()

# to know the number of rows and columns
dp.shape

# define the data type for each columns
dp.dtypes

# gives the index used
dp.index

# gives the columns name used
dp.columns

#iloc - integer location
# In data frames , iloc gives index values which is the row values .
dp.iloc[2]

# transporting the data frames
t=dp.T
t

# AND operator & = checks both condition and returns the output

dp[(dp['diabetes'] > 0) & (dp['age'] >40 )]

# OR operator | = checks any one of the condition and returns the output

dp[(dp['diabetes'] > 0) | (dp['hypertension'] >1 )]

# mean = gives avg value
# median = gives middle most value
# mode = gives the most repeating value
mean=dp['age'].mean()
median=dp['age'].median()
mode=dp['age'].mode()
print(mean)
print(median)
print(mode)

#generate descriptive statistics

dp.describe()

#count the unique values in diabetes column

dp['diabetes'].value_counts()

#count the unique values in smoking_history column

dp['smoking_history'].value_counts()

#check if there is missing values
dp.isnull().sum()

#check if there is dublicated data
dp.duplicated()

#check the number of duplicated data
dp.duplicated().sum()

#remove duplicates

dp.drop_duplicates()

dp.duplicated().sum()

# univariant analysis
# Countplot

sns.countplot(x=dp['gender'],data=dp )
plt.xlabel('Gender')
plt.title(' COUNT PLOT -Gender Distribution')
plt.show()

# 1. Distribution of numerical variables
numerical_columns = ['age', 'bmi', 'HbA1c_level', 'blood_glucose_level']
dp[numerical_columns].hist(bins=20, figsize=(14, 8), color='skyblue', edgecolor='black')
plt.suptitle('Distribution of Numerical Variables')
plt.show()

# 2. Pie Chart
data_counts = dp['gender'].value_counts()
plt.pie(data_counts, labels=data_counts.index, autopct='%1.2f%%')
plt.title('Pie Chart')
plt.show()

sns.countplot(x=dp['smoking_history'], hue=dp['diabetes'], data=dp ,palette='vlag' )

plt.title('countplot of smoking history with respect to diabetes')

plt.show()



# Box plot

sns.boxplot(data=dp[['age']])
plt.title('Box Plot of Age')
plt.xlabel('Age')
plt.ylabel('Values')
plt.show()



# Box plot

sns.boxplot(data=dp[['blood_glucose_level']])
plt.title('Box Plot')
plt.xlabel('Blood Glucose Level')
plt.ylabel('Values')
plt.show()



sns.lineplot(data=dp, x='age', y='HbA1c_level', hue='diabetes')
plt.title(' LINE PLOT - Age vs HbA1c Level')
plt.show()



# Calculate correlation matrix only for numeric columns
correlation_matrix = dp.select_dtypes(include=['number']).corr()  # Include only numeric columns for correlation calculation

sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

"""      Thats all with the generative description of various operations and EDA insights .


            **   THANK YOU    **
            




"""

